#!/usr/bin/env python3
"""Regenerate Sources/UsageCostCore/PricingCatalog.swift from LiteLLM's
model price list (MIT). Only Anthropic and OpenAI models are kept: the ones
Claude Code and Codex log. Usage: python3 scripts/update-pricing.py [json]"""
import datetime
import json
from pathlib import Path
import sys
import urllib.request

URL = 'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json'
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'Sources/UsageCostCore/PricingCatalog.swift'
PREFIXES = ('claude-', 'gpt-', 'o1', 'o3', 'o4', 'codex-')
FIELDS = {
    'input': 'input_cost_per_token',
    'output': 'output_cost_per_token',
    'cacheRead': 'cache_read_input_token_cost',
    'cacheWrite': 'cache_creation_input_token_cost',
    'cacheWrite1h': 'cache_creation_input_token_cost_above_1hr',
    'inputAbove200k': 'input_cost_per_token_above_200k_tokens',
    'outputAbove200k': 'output_cost_per_token_above_200k_tokens',
    'cacheReadAbove200k': 'cache_read_input_token_cost_above_200k_tokens',
    'cacheWriteAbove200k': 'cache_creation_input_token_cost_above_200k_tokens',
}


def main():
    if len(sys.argv) > 1:
        data = json.loads(Path(sys.argv[1]).read_text())
    else:
        with urllib.request.urlopen(URL, timeout=30) as response:
            data = json.load(response)
    rows = []
    for key in sorted(data):
        entry = data[key]
        if '/' in key or not key.startswith(PREFIXES) or not isinstance(entry, dict):
            continue
        if entry.get('litellm_provider') not in ('anthropic', 'openai'):
            continue
        if entry.get('input_cost_per_token') is None or entry.get('output_cost_per_token') is None:
            continue
        args = ', '.join(f'{name}: {entry[field]!r}' for name, field in FIELDS.items()
                         if entry.get(field) is not None)
        rows.append(f'        "{key}": ModelPrice({args}),')
    today = datetime.date.today().isoformat()
    OUT.write_text(
        f'// Generated by scripts/update-pricing.py from LiteLLM (MIT) on {today}.\n'
        '// Do not edit by hand; rerun the script to refresh prices.\n\n'
        'extension Pricing {\n'
        '    /// USD per token, keyed by model name.\n'
        '    public static let catalog: [String: ModelPrice] = [\n'
        + '\n'.join(rows) + '\n'
        '    ]\n'
        '}\n')
    print(f'wrote {len(rows)} models to {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
