#!/usr/bin/env python3
"""Regenerate Sources/UsageCostCore/PricingCatalog.swift from LiteLLM's
model price list (MIT). Only Anthropic and OpenAI models are kept: the ones
Claude Code and Codex log. Usage: python3 scripts/update-pricing.py [json]"""
import datetime
import json
from pathlib import Path
import re
import sys
import urllib.request

URL = 'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json'
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'Sources/UsageCostCore/PricingCatalog.swift'
PREFIXES = ('claude-', 'gpt-', 'o1', 'o3', 'o4', 'codex-')
FIELDS = {
    'input': 'input_cost_per_token',
    'output': 'output_cost_per_token',
    'cacheRead': 'cache_read_input_token_cost',
    'cacheWrite': 'cache_creation_input_token_cost',
    'cacheWrite1h': 'cache_creation_input_token_cost_above_1hr',
}
LONG = re.compile(r'^input_cost_per_token_above_(\d+)k_tokens$')
# Not in LiteLLM. Anthropic bills fast mode at twice the standard input and
# output rates, with the prompt caching multipliers on top, so every token
# kind doubles: https://platform.claude.com/docs/en/about-claude/pricing#fast-mode-pricing
FAST_MULTIPLIER = {'claude-opus-5-5': 2.0, 'claude-opus-5': 2.0, 'claude-opus-4-8': 2.0}


def rates(entry, long_suffix='', tier_suffix=''):
    """Swift `Rates(...)` for one tier and context length, or None."""
    values = {}
    for name, field in FIELDS.items():
        value = entry.get(field + long_suffix + tier_suffix)
        if value is not None:
            values[name] = value
    if 'input' not in values or 'output' not in values:
        return None
    return 'Rates(' + ', '.join(f'{name}: {value!r}' for name, value in values.items()) + ')'


def model_price(key, entry):
    standard = rates(entry)
    if standard is None:
        return None
    args = [f'standard: {standard}']
    threshold = next((int(m.group(1)) for field in entry if (m := LONG.match(field))), None)
    long_suffix = f'_above_{threshold}k_tokens' if threshold else None
    if long_suffix and (long := rates(entry, long_suffix)):
        args += [f'longContext: {long}', f'longContextThreshold: {threshold * 1000}']
    for tier in ('priority', 'flex'):
        if tiered := rates(entry, tier_suffix=f'_{tier}'):
            args.append(f'{tier}: {tiered}')
        if long_suffix and (tiered_long := rates(entry, long_suffix, f'_{tier}')):
            args.append(f'{tier}LongContext: {tiered_long}')
    if key in FAST_MULTIPLIER:
        args.append(f'fastMultiplier: {FAST_MULTIPLIER[key]!r}')
    return 'ModelPrice(\n            ' + ',\n            '.join(args) + ')'


def main():
    if len(sys.argv) > 1:
        data = json.loads(Path(sys.argv[1]).read_text())
    else:
        with urllib.request.urlopen(URL, timeout=30) as response:
            data = json.load(response)
    rows = []
    for key in sorted(data):
        entry = data[key]
        if '/' in key or not key.startswith(PREFIXES) or not isinstance(entry, dict):
            continue
        if entry.get('litellm_provider') not in ('anthropic', 'openai'):
            continue
        if price := model_price(key, entry):
            rows.append(f'        "{key}": {price},')
    today = datetime.date.today().isoformat()
    OUT.write_text(
        f'// Generated by scripts/update-pricing.py from LiteLLM (MIT) on {today}.\n'
        '// Do not edit by hand; rerun the script to refresh prices.\n\n'
        'extension Pricing {\n'
        '    /// USD per token, keyed by model name.\n'
        '    public static let catalog: [String: ModelPrice] = [\n'
        + '\n'.join(rows) + '\n'
        '    ]\n'
        '}\n')
    print(f'wrote {len(rows)} models to {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
